-- Loottracker shared + feature constants (dpsreview-style namespace).
local LT = _G.__LOOT_TRACKER or {}
_G.__LOOT_TRACKER = LT

local C = {
	-- Shared bag / resize / scale
	BAG_KIND = 1,
	MAX_BAG_SLOTS = 150,
	CORNER_HANDLE_SIZE = 18,
	RESIZE_GRIP_LINE_ALPHA = 0,
	RESIZE_GRIP_HOVER_ALPHA = 0.65,
	RESIZE_GRIP_LINE_LENGTH = 9,
	RESIZE_GRIP_LINE_THICKNESS = 2,
	RESIZE_GRIP_INSET = 5,
	MIN_WINDOW_SCALE = 0.85,
	MAX_WINDOW_SCALE = 1.35,

	-- Tracker CONFIG
	SAVE_KEY = "lootTrackerTrackedItems",
	POSITION_KEY = "lootTrackerWindowPosition",
	RESTORE_POSITION_KEY = "lootTrackerRestoreButtonPosition",
	PICKER_POSITION_KEY = "lootTrackerPickerWindowPosition",
	SET_WINDOW_POSITION_KEY = "lootTrackerSetWindowPosition",
	LAYOUT_KEY = "lootTrackerLayout",
	MENU_MODE_KEY = "lootTrackerEscMenuMode",
	WINDOW_VISIBLE_KEY = "lootTrackerWindowVisible",
	SETS_KEY = "lootTrackerTrackedItemSets",
	ACTIVE_SET_KEY = "lootTrackerActiveSetName",
	DROP_RATE_KEY = "drop_rate_mul",
	SLOT_COUNT_KEY = "lootTrackerSlotCount",
	WINDOW_SCALE_KEY = "lootTrackerWindowScale",

	LAYOUT_HORIZONTAL = "horizontal",
	LAYOUT_VERTICAL = "vertical",
	ESC_MENU_CATEGORY_ID = 3,
	ESC_MENU_CONTENT_ID = 1552,
	ESC_MENU_ICON_KEY = "bag",
	ESC_MENU_BUTTON_NAME = "Loot Tracker",
	RESTORE_BUTTON_WIDTH = 92,
	RESTORE_BUTTON_HEIGHT = 22,
	PADDING = 9,
	TRACKER_PADDING = 4,
	TRACKER_TOP_PADDING = 1,
	HEADER_HEIGHT = 22,
	HEADER_TITLE_WIDTH = 78,
	HEADER_BUTTON_GAP = 4,
	HEADER_BUTTON_HEIGHT = 18,
	ROTATE_BUTTON_WIDTH = 24,
	RESET_BUTTON_WIDTH = 24,
	MENU_BUTTON_WIDTH = 34,
	HIDE_WINDOW_BUTTON_WIDTH = 34,
	SET_BUTTON_WIDTH = 24,
	LOOT_RATE_MARKER_WIDTH = 48,
	LOOT_RATE_MARKER_HEIGHT = 18,
	LOOT_RATE_TEXT_COLOR = { 0.28, 1.0, 0.36, 1 },
	TRACKED_DROP_RATE_IDLE_RESET_SECONDS = 120.0,
	TRACKED_DROP_RATE_LABEL_HEIGHT = 14,
	TRACKED_DROP_RATE_LABEL_FONT_SIZE = 9,
	TRACKED_DROP_RATE_TEXT_COLOR = { 0.28, 1.0, 0.36, 1 },
	TRACKED_SESSION_COUNT_TEXT_COLOR = { 0.72, 0.42, 1.0, 1 },
	BOX_SIZE = 40,
	BOX_GAP = 6,
	TRACKER_ROW_TOP_GAP = 3,
	ACQUISITION_GLOW_SECONDS = 40.0,
	ACQUISITION_GLOW_BATCH_SECONDS = 2.0,
	ACQUISITION_GLOW_MAX_ALPHA = 0.8,
	ACQUISITION_GLOW_BORDER_SIZE = 3,
	ACQUISITION_GLOW_COLOR = { 1.0, 0.41, 0.71 },
	ACQUISITION_GLOW_INNER_COLOR = { 0.72, 0.48, 0.95 },
	ACQUISITION_GLOW_INNER_GRADIENT_STEPS = 2,
	ACQUISITION_GLOW_INNER_STEP_SIZE = 2.35,
	ACQUISITION_GLOW_INNER_MAX_ALPHA = 0.5,
	LOOT_ACTIVITY_FRESH_SECONDS = 2.0,

	PICKER_WIDTH = 330,
	PICKER_HEIGHT = 328,
	PICKER_COLUMNS = 3,
	PICKER_ROWS = 5,
	PICKER_ITEM_WIDTH = 96,
	PICKER_ITEM_HEIGHT = 34,
	PICKER_ITEM_GAP_X = 6,
	PICKER_ITEM_GAP_Y = 6,
	PICKER_SEARCH_TOP = 42,
	PICKER_SEARCH_HEIGHT = 30,
	PICKER_GRID_TOP = 84,
	SET_WINDOW_WIDTH = 200,
	SET_WINDOW_MIN_HEIGHT = 132,
	SET_ROW_TOP = 104,
	SET_ROW_HEIGHT = 26,
	SET_ROW_GAP = 4,
	SET_WINDOW_PADDING = 10,
	SET_ACTION_BUTTON_HEIGHT = 22,
	SET_SAVE_BUTTON_WIDTH = 44,
	SET_OVERWRITE_BUTTON_WIDTH = 88,
	SET_DELETE_BUTTON_WIDTH = 36,
	SET_STATUS_OUTSIDE_GAP = 4,
	SET_NAME_CHAR_WIDTH = 7,
	SET_NAME_TEXT_MAX_WIDTH = 136,
	MAX_TRACKED_SET_COUNT = 40,
	SET_VISIBLE_ROWS = 10,
	INVENTORY_FALLBACK_REFRESH_SECONDS = 10.0,
	INVENTORY_EVENT_DEBOUNCE_SECONDS = 0.15,
	INVENTORY_EVENT_MAX_DEFER_SECONDS = 0.75,
	RESIZE_UPDATE_INTERVAL = 0.05,
	RESIZE_SCALE_EPSILON = 0.01,
	SEARCH_POLL_INTERVAL = 0.12,

	DEFAULT_TRACKED_SLOT_COUNT = 5,

	ITEM_ID_FIELD_NAMES = {
		"itemType",
		"item_type",
		"itemTypeId",
		"item_type_id",
		"itemId",
		"item_id",
		"id",
		"type",
	},
	ICON_FIELD_NAMES = {
		"iconPath",
		"icon_path",
		"itemIconPath",
		"item_icon_path",
		"iconFilePath",
		"icon_file_path",
		"texturePath",
		"texture_path",
		"itemTexturePath",
		"item_texture_path",
		"icon",
		"itemIcon",
		"item_icon",
		"iconFile",
		"icon_file",
		"iconTexture",
		"icon_texture",
		"texture",
		"itemTexture",
		"item_texture",
		"path",
		"image",
		"imagePath",
		"image_path",
	},
	COUNT_FIELD_NAMES = {
		"stackCount",
		"stack_count",
		"itemCount",
		"item_count",
		"quantity",
		"amount",
		"count",
		"stack",
	},
}

C.BOXES_TOP = C.TRACKER_TOP_PADDING + C.HEADER_HEIGHT + C.TRACKER_ROW_TOP_GAP
C.PICKER_VISIBLE_COUNT = C.PICKER_COLUMNS * C.PICKER_ROWS
C.PICKER_CONTROL_TOP = C.PICKER_GRID_TOP
	+ (C.PICKER_ROWS * (C.PICKER_ITEM_HEIGHT + C.PICKER_ITEM_GAP_Y))
C.SET_WINDOW_CONTENT_WIDTH = C.SET_WINDOW_WIDTH - (C.SET_WINDOW_PADDING * 2)

-- Kill-counter constants (distinct save keys / timings / zones).
local KC = {
	SAVE_KEY = "lootKillCounterKills",
	SETTINGS_SAVE_KEY = "lootKillCounterSettings",
	HISTORY_SAVE_KEY = "lootKillCounterHistory",
	WINDOW_POSITION_KEY = "lootKillCounterWindowPosition",
	WINDOW_SIZE_KEY = "lootKillCounterWindowSize",
	VIEW_WINDOW_POSITION_KEY = "lootKillCounterViewWindowPosition",
	WINDOW_WIDTH = 286,
	WINDOW_HEIGHT = 272,
	MIN_WINDOW_WIDTH = 270,
	MIN_WINDOW_HEIGHT = 250,
	VIEW_WINDOW_WIDTH = 440,
	VIEW_WINDOW_HEIGHT = 560,
	VIEW_ROW_TOP = 76,
	VIEW_ROW_HEIGHT = 15,
	VIEW_CONTENT_ROW_COUNT = 31,
	VIEW_SEGMENT_CHAR_WIDTH = 7,
	MONEY_GOLD_COLOR = { 1.0, 0.82, 0.20, 1 },
	MONEY_SILVER_COLOR = { 0.72, 0.78, 0.84, 1 },
	MONEY_COPPER_COLOR = { 0.86, 0.48, 0.24, 1 },
	MONEY_LABEL_COLOR = { 0.90, 0.86, 0.72, 1 },
	BAG_KIND = C.BAG_KIND,
	MAX_BAG_SLOTS = C.MAX_BAG_SLOTS,
	PADDING = 10,
	ROW_TOP = 48,
	ROW_HEIGHT = 20,
	PAGE_SIZE = 8,
	CORNER_HANDLE_SIZE = C.CORNER_HANDLE_SIZE,
	RESIZE_GRIP_LINE_ALPHA = C.RESIZE_GRIP_LINE_ALPHA,
	RESIZE_GRIP_HOVER_ALPHA = C.RESIZE_GRIP_HOVER_ALPHA,
	RESIZE_GRIP_LINE_LENGTH = C.RESIZE_GRIP_LINE_LENGTH,
	RESIZE_GRIP_LINE_THICKNESS = C.RESIZE_GRIP_LINE_THICKNESS,
	RESIZE_GRIP_INSET = C.RESIZE_GRIP_INSET,
	MIN_WINDOW_SCALE = C.MIN_WINDOW_SCALE,
	MAX_WINDOW_SCALE = C.MAX_WINDOW_SCALE,
	DAMAGE_RECENT_SECONDS = 20,
	TARGET_CACHE_SECONDS = 12,
	LOOT_ATTRIBUTION_SECONDS = 20,
	EXP_ATTRIBUTION_SECONDS = 8,
	PLAYER_COMBAT_EXIT_GRACE = 1.5,
	EXP_COMBAT_LOG_TIMEOUT = 10,
	PENDING_CAPTURE_DEDUPE_SECONDS = 0.35,
	MONEY_EVENT_DEDUPE_SECONDS = 0.35,
	MAX_PENDING_HITS_PER_TARGET = 4,
	MAX_PENDING_HITS_TOTAL = 20,
	PROJECTILE_CAPTURE_REASONS = {
		SPELLCAST_START = true,
		SPELLCAST_SUCCEEDED = true,
		target_switch = true,
	},
	FULL_HEALTH_CAPTURE_REASONS = {
		SPELLCAST_START = true,
		SPELLCAST_SUCCEEDED = true,
		target_switch = true,
	},
	DAMAGE_CATEGORY_ORDER = { "Melee", "Spell", "Ranged", "Environmental", "Other" },
}

KC.ZONE_GROUP_NAMES = {
	[1] = "Gweonid Forest",
	[2] = "Marianople",
	[3] = "Dewstone Plains",
	[4] = "Solis Headlands",
	[5] = "Solzreed Peninsula",
	[6] = "Lilyut Hills",
	[7] = "Arcum Iris",
	[8] = "Two Crowns",
	[9] = "Mahadevi",
	[10] = "Airain Rock",
	[11] = "Falcorth Plains",
	[12] = "Villanelle",
	[13] = "Sunbite Wilds",
	[14] = "Windscour Savannah",
	[15] = "Perinoor Ruins",
	[16] = "Rookborne Basin",
	[17] = "Ynystere",
	[18] = "White Arden",
	[19] = "Karkasse Ridgelands",
	[20] = "Cinderstone Moor",
	[21] = "Aubre Cradle",
	[22] = "Halcyona",
	[23] = "Hasla",
	[24] = "Tigerspine Mountains",
	[25] = "Silent Forest",
	[26] = "Hellswamp",
	[27] = "Sanddeep",
	[28] = "The Wastes",
	[29] = "Libertia Sea",
	[30] = "Castaway Strait",
	[31] = "Drill Camp",
	[32] = "Dreadnought",
	[33] = "Heedmar",
	[34] = "Nuimari",
	[36] = "Arcadian Sea",
	[39] = "Halcyona Gulf",
	[40] = "Feuille Sound",
	[41] = "Forbidden Sea",
	[42] = "Forbidden Shore",
	[43] = "Marcala",
	[44] = "Calmlands",
	[45] = "Burnt Castle Armory",
	[46] = "Hadir Farm",
	[47] = "Palace Cellar",
	[48] = "Saltswept Atoll",
	[49] = "Mirage Isle",
	[50] = "Sharpwind Mines",
	[51] = "Howling Abyss",
	[52] = "Kroloal Cradle",
	[53] = "Violent Maelstrom Arena",
	[54] = "Exeloch",
	[55] = "Serpentis",
	[56] = "Sungold Fields",
	[57] = "Golden Ruins",
	[58] = "Greater Howling Abyss",
	[59] = "Sunspeck Sea",
	[60] = "Stormraw Sound",
	[61] = "Diamond Shores",
	[62] = "Sea of Drowned Love",
	[63] = "Reedwind",
	[64] = "Lesser Sea of Drowned Love",
	[65] = "Verdant Skychamber",
	[66] = "Lesser Serpentis",
	[67] = "Introspect Path",
	[68] = "Lucius's Dream",
	[69] = "Evening Botanica",
	[70] = "Encyclopedia Room",
	[71] = "Libris Garden",
	[72] = "Screaming Archives",
	[73] = "Screening Hall",
	[74] = "Frozen Study",
	[75] = "Deranged Bookroom",
	[76] = "Corner Reading Room",
	[77] = "Gladiator Arena",
	[78] = "Mistmerrow",
	[79] = "Miroir Tundra",
	[80] = "Shattered Sea",
	[81] = "New Arena",
	[82] = "Epherium",
	[83] = "Greater Hadir Farm",
	[84] = "Greater Burnt Castle Armory",
	[85] = "Heart of Ayanad",
	[86] = "Greater Palace Cellar",
	[87] = "Greater Sharpwind Mines",
	[88] = "Greater Kroloal Cradle",
	[89] = "Mistsong Summit",
	[90] = "Arena",
	[91] = "Decisive Arena",
	[92] = "Free-For-All Arena",
	[93] = "Ahnimar",
	[94] = "Ancient Ezna",
	[95] = "Boiling Sea",
	[96] = "Sylvina Caldera",
	[97] = "Bloodsalt Bay",
	[98] = "Queen's Chamber",
	[99] = "Rokhala Mountains",
	[100] = "Queen's Chamber",
	[101] = "Burnt Castle Cellar",
	[102] = "Aegis Island",
	[103] = "Whalesong Harbor",
	[104] = "Whaleswell Straits",
	[105] = "Ipnysh Sanctuary",
	[106] = "Snowball Arena",
	[107] = "Western Hiram Mountains",
	[108] = "Golden Plains Battle",
	[109] = "Golden Plains Battle",
	[110] = "Eastern Hiram Mountains",
	[111] = "Screening Hall (Disabled)",
	[112] = "Frozen Study (Disabled)",
	[113] = "Deranged Bookroom (Disabled)",
	[114] = "Corner Reading Room (Disabled)",
	[115] = "Heart of Ayanad (Disabled)",
	[116] = "Unused",
	[117] = "Verdant Skychamber (Disabled)",
	[118] = "Evening Botanica (Disabled)",
	[119] = "Constellation Breakroom (Disabled)",
	[120] = "Abyssal Library",
	[121] = "Red Dragon's Keep",
	[122] = "The Fall of Hiram City",
	[125] = "Noryette Challenge",
	[126] = "Mistsong Banquet",
	[127] = "Naval Survival Game (test)",
	[129] = "Stillwater Gulf",
	[130] = "Hereafter Rebellion",
	[131] = "Battle of Mistmerrow",
	[132] = "Kadum",
	[133] = "Garden of the Gods",
	[134] = "Gatekeeper Hall",
	[135] = "Dairy Cow Dreamland",
	[136] = "Circle of Authority",
	[137] = "Delphinad Mirage",
	[138] = "Test Arena",
	[139] = "Mysthrane Gorge",
	[140] = "Ipnya Ridge",
	[141] = "Skyfin War",
	[142] = "Queen's Altar",
	[143] = "Event Arena",
	[144] = "Guild House",
	[145] = "Unused",
	[146] = "Black Thorn Prison",
	[147] = "Great Prairie of the West",
	[148] = "Greater Serpentis",
	[149] = "Squid Game Event Arena",
	[150] = "Dimensional Boundary Defense Raid",
	[151] = "Ahnimar Event Arena",
	[152] = "Goldleaf Forest",
	[153] = "Make a Splash",
	[154] = "Nightmare Burnt Castle Armory",
	[155] = "Crossroads Arena",
	[156] = "Noryette Arena",
	[158] = "Island of Abundance",
	[159] = "Golden Plains Battle",
}

LT.C = C
LT.KC = KC
